name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Check Gradle
        run: ./gradlew --version

      - name: Show Tasks
        run: ./gradlew tasks --all

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --info --console=plain

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease --stacktrace --info --console=plain

      - name: Build Release AAB
        run: ./gradlew :app:bundleRelease --stacktrace --info --console=plain

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: APK
          path: |
            android/app/build/outputs/apk/**/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: AAB
          path: |
            android/app/build/outputs/bundle/**/*.aab

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Reports
          path: |
            android/build/reports/**
            android/app/build/reports/**
